/*
 * File: app/view/MainNav.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CityBarsPlus.view.MainNav', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainnav',
    requires: [
        'CityBarsPlus.view.ListContainer'
    ],

    config: {
        id: 'mainnav',
        navigationBar: {
            ui: 'light',
            items: [
                {
                    xtype: 'button',
                    id: 'logOut',
                    itemId: 'logOut',
                    iconCls: 'delete',
                    iconMask: true,
                    text: '',
                    align: 'right'
                }
            ]
        },
        items: [
            {
                xtype: 'listcontainer',
                title: 'City Bars'
            }
        ],
        listeners: [
            {
                fn: 'onLogOutTap',
                event: 'tap',
                delegate: '#logOut'
            }
        ]
    },

    onLogOutTap: function(button, e, options) {
        Ext.getCmp('mainnav').reset();
        Ext.Viewport.setActiveItem(0);
    }

});