/*
 * File: app/view/searchForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CityBarsPlus.view.searchForm', {
    extend: 'Ext.Container',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'searchSet',
                itemId: 'searchSet',
                items: [
                    {
                        xtype: 'fieldset',
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'inputCategory',
                                itemId: 'inputCategory',
                                label: 'Search for...',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'textfield',
                                id: 'inputCity',
                                itemId: 'inputCity',
                                label: 'Where?',
                                labelWidth: '40%'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        disabled: true,
                        id: 'searchButton',
                        itemId: 'searchButton',
                        ui: 'confirm',
                        text: 'Search'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        ui: 'light',
                        title: 'City Bars',
                        layout: {
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'geoLocate',
                                itemId: 'mybutton4',
                                iconCls: 'locate',
                                iconMask: true,
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onGeoLocateTap',
                event: 'tap',
                delegate: '#geoLocate'
            }
        ]
    },

    onGeoLocateTap: function(button, e, options) {
        if(navigator.geolocation){

            Ext.getCmp('inputCity').setValue('Loading...');

            navigator.geolocation.getCurrentPosition(function(pos) {
                var lat = pos.coords.latitude;
                var long = pos.coords.longitude;
                var geocoder = new google.maps.Geocoder();
                var latlng = new google.maps.LatLng(lat, long);
                var city = '';
                var region = '';

                geocoder.geocode({'latLng': latlng}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    console.log(results);
                    if(results.length > 0) {
                        city = results[0].address_components[2].short_name;
                        region = results[0].address_components[4].short_name;
                        console.log(city, region);
                        Ext.getCmp('inputCity').setValue(city+', '+region);
                    }
                } else {
                    alert("Could not get your location... sorry!");
                    Ext.getCmp('inputCity').setValue('');
                }
            });
        });
    }
    }

});